### ISSUE TITLE
Spacing between romanized words

### ISSUE THREAD

**Issue by kurisubrooks** [hakatashi/japanese.js#10]
Currently when using this module, `じしんがはっぴょうされました` → `jishingahappyōsaremashita`, however it would be better if it returned with romanized spacing, like `jishin ga happyō saremashita`.

Would this be possible?

https://github.com/lovell/hepburn has spacing:
`これはテスト。おまえはあほです。ほんとうばか！` → `kore wa tesuto. omae wa aho desu. hontoo baka!`

However your module returns
`これはテスト。おまえはあほです。ほんとうばか！` → `korehatesuto.omaehaahodesu.hontōbaka`

**Comment by hakatashi** [comment]
> Would this be possible?

No. And not in future too.

Spacing of natural Japanese text demands morphological analysis of the sentence. That faculty will be bundled with huge dictionary of Japanese words and not suitable for this small module.

I recommend [kuromojin](https://github.com/azu/kuromojin) for such usage.

```js
const kuromojin = require('kuromojin');
const japanese = require('japanese');

kuromojin.tokenize('これはテスト。おまえはあほです。ほんとうばか！').then(tokens => {
    console.log(tokens.map(token => japanese.romanize(token.reading)).join(' '));
    // prints 'kore ha tesuto . omae ha a ho desu . hontō baka'
});
```

> https://github.com/lovell/hepburn has spacing

I couldn't confirm the module has spacing.
https://tonicdev.com/hakatashi/hepburn-test

**Comment by hakatashi** [comment]
Anyway, thanks for your feedback :grinning:
